directories:
  output: release
  buildResources: build
appId: com.akordyar.app
productName: Akordyar
copyright: Copyright © 2026 Akordyar
files:
  - filter:
      - electron-main.js
      - server.js
      - parser-test.js
      - Akordyar.html
      - package.json
      - js/**/*
      - styles/**/*
      - build/icon.png
      - build/icon.ico
      - node_modules/express/**/*
      - node_modules/jsdom/**/*
asar: false
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Akordyar
  deleteAppDataOnUninstall: false
portable:
  artifactName: Akordyar-Portable-${version}.exe
electronVersion: 31.7.7
